### ISSUE TITLE
Dependency on catbus

### ISSUE THREAD

**Issue by ajmiciano** [catawiki/fake-kafka#10]
I'm trying to use the gem, but I'm getting an error related to Catbus, I don't know what it is, can you help me?
`uninitialized constant Catbus`

**Comment by skrobul** [comment]
I know it's almost 2 years later and you probably don't need it anymore, but looks like `Catbus` is probably just a reference to some internal [Catawiki's](https://github.com/catawiki) project, so the README file is slightly misleading. 
If I understood correctly, the way to use it would be:

1. Adapt your existing code that is responsible for creating Consumer/Producer/Client instance to refer to `Kafka` class indirectly
2. Dynamically check if it needs to use real `Kafka` or `Fake::Kafka` classes, for example based on the env variable.

For example, if you normally create client with
```ruby
client = Kafka::Client.new(brokers: '1.1.1.1')
```
you would implement a class like that:

**initialization code - run always**
```ruby
class Dogbus
  class << self
    attr_accessor :kafka_driver
  end
end
Dogbus.kafka_driver = Kafka
```

then you would change your original code to:

```ruby
client = Dogbus.kafka_driver.new(brokers: '1.1.1.1')
```

and finally, for testing, for example in **spec_helper.rb** you would do:
```ruby
Dogbus.kafka_driver = Fake::Kafka
```

**Comment by ajmiciano** [comment]
> I know it's almost 2 years later and you probably don't need it anymore, but looks like `Catbus` is probably just a reference to some internal [Catawiki's](https://github.com/catawiki) project, so the README file is slightly misleading. If I understood correctly, the way to use it would be:
> 
> 1. Adapt your existing code that is responsible for creating Consumer/Producer/Client instance to refer to `Kafka` class indirectly
> 2. Dynamically check if it needs to use real `Kafka` or `Fake::Kafka` classes, for example based on the env variable.
> 
> For example, if you normally create client with
> 
> ```ruby
> client = Kafka::Client.new(brokers: '1.1.1.1')
> ```
> 
> you would implement a class like that:
> 
> **initialization code - run always**
> 
> ```ruby
> class Dogbus
>   class << self
>     attr_accessor :kafka_driver
>   end
> end
> Dogbus.kafka_driver = Kafka
> ```
> 
> then you would change your original code to:
> 
> ```ruby
> client = Dogbus.kafka_driver.new(brokers: '1.1.1.1')
> ```
> 
> and finally, for testing, for example in **spec_helper.rb** you would do:
> 
> ```ruby
> Dogbus.kafka_driver = Fake::Kafka
> ```

Thanks for the answer!
